# OpenAL Soft settings for the Miyoo Mini Plus (OSS via OnionOS's audioserver)
[general]
drivers = oss
channels = stereo
frequency = 44100
period_size = 1024
periods = 3
resampler = linear
sources = 64
hrtf = false

[oss]
device = /dev/dsp
